# Generated by Django 3.1.7 on 2021-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='fintech',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Fintech'),
        ),
    ]
