# Generated by Django 3.1.7 on 2021-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_estudio_fintech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rating', models.IntegerField()),
                ('reting_total', models.IntegerField()),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
                ('placeID', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la publicación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última edición')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Texto del tweet')),
                ('retweets', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('quotes', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('placeID', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la publicación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última edición')),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='tweets',
            field=models.ManyToManyField(related_name='get_tweets', to='studies.Tweet', verbose_name='Tweet'),
        ),
    ]
