# Generated by Django 3.1.7 on 2021-04-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20210420_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='John Doe', max_length=300, verbose_name='Nombre del user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='latitud',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='longitud',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='placeID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='placeID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
