# Generated by Django 3.1.7 on 2021-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20210420_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
