# Generated by Django 3.1.7 on 2021-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_tweet_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
