# Generated by Django 3.1.7 on 2021-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_estudio_lenguaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la categoria')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de la última edición')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la review'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='studies.Category', verbose_name='Categorías'),
        ),
    ]
