# Generated by Django 3.1.7 on 2021-04-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_auto_20210423_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'sector', 'verbose_name_plural': 'sectores'},
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='categories',
            field=models.ManyToManyField(related_name='get_estudios', to='studies.Category', verbose_name='Tipo de empresa'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='lenguaje',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('pt', 'Portugués')], default='es', max_length=10, verbose_name='Lenguaje de estudio de tweets'),
        ),
    ]
