# Generated by Django 3.1.7 on 2021-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_auto_20210424_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
