# Generated by Django 3.1.7 on 2021-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_auto_20210426_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='graph2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='graph9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
