# Generated by Django 3.1.7 on 2021-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_auto_20210426_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='graph10',
            field=models.TextField(blank=True, null=True),
        ),
    ]
