# Generated by Django 3.1.7 on 2021-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_auto_20210501_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='neg_sen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='neu_sen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='pos_sen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
