# Generated by Django 3.1.7 on 2021-05-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0015_auto_20210501_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='sen_predominant',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
