# Generated by Django 3.1.7 on 2021-05-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_estudio_sen_predominant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='lenguaje',
        ),
    ]
