# Generated by Django 3.1.7 on 2021-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_remove_estudio_lenguaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='url',
        ),
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='Anónimo', max_length=300, verbose_name='Nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='Anónimo', max_length=300, verbose_name='Username'),
        ),
    ]
