# Generated by Django 3.2.2 on 2021-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_auto_20210503_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
