# Generated by Django 3.2.2 on 2021-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0019_auto_20210506_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='error',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='fintech',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre de la Fintech'),
            preserve_default=False,
        ),
    ]
