# Generated by Django 3.2.2 on 2021-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0020_auto_20210507_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='fintech',
            field=models.CharField(default='None', max_length=50, verbose_name='Nombre de la Fintech'),
        ),
    ]
