# Generated by Django 3.2.2 on 2021-05-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0022_alter_estudio_fintech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reting_total',
            new_name='rating_total',
        ),
        migrations.AddField(
            model_name='review',
            name='country',
            field=models.TextField(default=None, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la sede'),
        ),
    ]
